USE [Data_Lab_SWL]
GO

/****** Object:  Table [Unified].[tbl_ED_EncounterDenormalised_Active]    Script Date: 12/01/2026 15:32:18 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [Unified].[tbl_ED_EncounterDenormalised_Active](
	[SK_EncounterID] [bigint] NULL,
	[dv_Extract_Type] [varchar](16) NOT NULL,
	[dv_Query_ID] [varchar](34) NULL,
	[dv_FinYear] [varchar](8000) NULL,
	[dv_FinMonth] [tinyint] NULL,
	[dv_Activity_Period_Date] [varchar](8) NULL,
	[CDS_Record_Type] [varchar](3) NULL,
	[Generated_Record_ID] [varchar](32) NULL,
	[Spell_Identifier] [varchar](32) NULL,
	[Unique_CDS_Identifier] [varchar](35) NULL,
	[EM_Attendance_Number] [varchar](32) NULL,
	[Arrival_Date] [datetime2](0) NULL,
	[Arrival_Time] [varchar](5) NULL,
	[EM_Referral_Source] [int] NOT NULL,
	[EM_Mode_of_Arrival] [varchar](18) NULL,
	[EM_Department_Type] [varchar](2) NULL,
	[EM_Attendance_Category] [varchar](1) NULL,
	[EM_Incident_Location_Type] [int] NULL,
	[EM_Patient_Group] [int] NULL,
	[EM_Staff_Member_Code] [int] NULL,
	[dv_EM_Initial_Assessment_Date] [datetime2](0) NULL,
	[EM_Initial_Assessment_Time] [varchar](8) NULL,
	[EM_Time_Seen_for_Treatment] [varchar](8) NULL,
	[dv_EM_Date_Seen_for_Treatment] [datetime2](0) NULL,
	[dv_EM_Attendance_Conclusion_Date] [datetime2](0) NULL,
	[EM_Attendance_Conclusion_Time] [varchar](8) NULL,
	[EM_Attendance_Disposal] [int] NULL,
	[EM_Departure_Date] [datetime2](0) NULL,
	[EM_Departure_Time] [varchar](8) NULL,
	[dv_EM_Conclusion_Waiting_Time] [int] NULL,
	[EM_Duration_Time] [int] NULL,
	[dv_EM_Treatment_Wait_Time] [int] NULL,
	[Number_Diagnosis] [int] NULL,
	[Number_Procedures] [int] NOT NULL,
	[SK_PatientID] [varchar](20) NULL,
	[DW_NHS_Number] [int] NULL,
	[CCG_NHS_Number] [int] NULL,
	[Local_Patient_Identifier] [varchar](32) NULL,
	[Carer_Support_Indicator] [int] NULL,
	[Ethnic_Category_Code] [varchar](2) NULL,
	[Age_At_CDS_Activity_Date] [smallint] NULL,
	[Gender_Code] [varchar](1) NULL,
	[Postcode_of_Usual_Address] [varchar](20) NULL,
	[dv_LSOA] [varchar](9) NULL,
	[Registered_GMP_Code_Original_Data] [varchar](8) NULL,
	[GP_Practice_Code] [varchar](12) NULL,
	[GP_Practice_Code_Original_Data] [varchar](12) NULL,
	[Provider_Reference_No] [varchar](20) NULL,
	[Commissioner_Reference_No] [varchar](20) NULL,
	[Commissioning_Serial_No_Agreement_No] [varchar](12) NULL,
	[NHS_Service_Agreement_Line_No] [varchar](10) NULL,
	[Organisation_Code_Code_of_Provider] [varchar](12) NULL,
	[Provider_Site_Code] [varchar](12) NULL,
	[Organisation_Code_Code_of_Commissioner] [varchar](12) NULL,
	[Organisation_Code_PCT_of_Residence] [varchar](12) NULL,
	[PCT_Derived_from_GP_Practice] [varchar](12) NULL,
	[Patient_Postcode_Derived_PCT] [varchar](12) NULL,
	[PCT_of_Residence_Original] [int] NULL,
	[PCT_Responsible] [varchar](12) NULL,
	[dv_CCAM_SWL] [int] NULL,
	[dv_Commissioner_Code_of_Residence] [int] NULL,
	[dv_Purchaser_ID] [int] NULL,
	[dv_Contract_Suffix] [int] NULL,
	[dv_CostMethodDescription] [int] NULL,
	[Core_HRG] [varchar](5) NULL,
	[dv_HRG] [int] NULL,
	[dv_Local_Cost_Code] [int] NULL,
	[dv_Reason_for_Difference] [int] NULL,
	[dv_IsPBR] [int] NULL,
	[dv_Base_Cost] [int] NULL,
	[dv_MFF_Index_Applied] [int] NULL,
	[Tariff_Initial_Amount_National] [smallint] NULL,
	[Tariff_Pre_MFF_Adjusted_National] [smallint] NULL,
	[Applied_MFF_National] [decimal](18, 6) NULL,
	[Tariff_Total_Payment_National] [smallint] NULL,
	[PBR_Final_Tariff] [smallint] NULL,
	[dv_Total_Cost_Inc_MFF] [int] NULL,
	[dv_AE_Arrival_DateTime] [datetime] NULL,
	[dv_AE_Departure_DateTime] [datetime] NULL,
	[DataAtInclusionPoint] [varchar](20) NULL,
	[LogId] [int] NULL
) ON [PRIMARY]
GO


