--USE [NHSE_Sandbox_Internal]  --Change this database name as appropriate
--GO

/****** Object:  Table [CAM_Ref].[SubICBtoDirectComm]    Script Date: 15/04/2025 08:04:32 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (
		SELECT * FROM INFORMATION_SCHEMA.TABLES
		WHERE TABLE_NAME = 'SubICBtoDirectComm' AND TABLE_SCHEMA = 'CAM_Ref')

		DROP TABLE [CAM_Ref].[SubICBtoDirectComm]

		CREATE TABLE [CAM_Ref].[SubICBtoDirectComm](
			[SubICB_Code] [varchar](10) NOT NULL,
			[ICB_Code] [varchar](10) NULL,
			[ODSCommHub] [varchar](3) NULL,
			[ODSRegion] [varchar](3) NULL,
			[ODSHealthandJustice] [varchar](3) NULL,
			[ProvisionalICBDelegationStatus] [varchar](3) NULL,
			[Effective_From] [date] NOT NULL,
			[Effective_To] [date] NULL,
		PRIMARY KEY CLUSTERED 
		(
			[SubICB_Code] ASC,
			[Effective_From] ASC
		)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
		) ON [PRIMARY]
GO

INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('00L','QHM','85J','Y63','76A','No','2024-04-01','2025-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('00L','QHM','85J','Y63','76A','Yes','2025-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('00N','QHM','85J','Y63','76A','No','2024-04-01','2025-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('00N','QHM','85J','Y63','76A','Yes','2025-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('00P','QHM','85J','Y63','76A','No','2024-04-01','2025-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('00P','QHM','85J','Y63','76A','Yes','2025-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('00Q','QE1','27T','Y62','32T','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('00R','QE1','27T','Y62','32T','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('00T','QOP','27T','Y62','32T','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('00V','QOP','27T','Y62','32T','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('00X','QE1','27T','Y62','32T','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('00Y','QOP','27T','Y62','32T','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('01A','QE1','27T','Y62','32T','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('01D','QOP','27T','Y62','32T','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('01E','QE1','27T','Y62','32T','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('01F','QYG','27T','Y62','32T','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('01G','QOP','27T','Y62','32T','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('01H','QHM','85J','Y63','76A','No','2024-04-01','2025-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('01H','QHM','85J','Y63','76A','Yes','2025-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('01J','QYG','27T','Y62','32T','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('01K','QE1','27T','Y62','32T','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('01T','QYG','27T','Y62','32T','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('01V','QYG','27T','Y62','32T','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('01W','QOP','27T','Y62','32T','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('01X','QYG','27T','Y62','32T','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('01Y','QOP','27T','Y62','32T','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('02A','QOP','27T','Y62','32T','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('02E','QYG','27T','Y62','32T','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('02G','QE1','27T','Y62','32T','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('02H','QOP','27T','Y62','32T','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('02M','QE1','27T','Y62','32T','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('02P','QF7','85J','Y63','76A','No','2024-04-01','2025-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('02P','QF7','85J','Y63','76A','Yes','2025-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('02Q','QT1','14A','Y60','14Q','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('02T','QWO','85J','Y63','76A','No','2024-04-01','2025-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('02T','QWO','85J','Y63','76A','Yes','2025-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('02X','QF7','85J','Y63','76A','No','2024-04-01','2025-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('02X','QF7','85J','Y63','76A','Yes','2025-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('02Y','QOQ','85J','Y63','76A','No','2024-04-01','2025-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('02Y','QOQ','85J','Y63','76A','Yes','2025-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('03F','QOQ','85J','Y63','76A','No','2024-04-01','2025-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('03F','QOQ','85J','Y63','76A','Yes','2025-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('03H','QOQ','85J','Y63','76A','No','2024-04-01','2025-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('03H','QOQ','85J','Y63','76A','Yes','2025-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('03K','QOQ','85J','Y63','76A','No','2024-04-01','2025-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('03K','QOQ','85J','Y63','76A','Yes','2025-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('03L','QF7','85J','Y63','76A','No','2024-04-01','2025-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('03L','QF7','85J','Y63','76A','Yes','2025-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('03N','QF7','85J','Y63','76A','No','2024-04-01','2025-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('03N','QF7','85J','Y63','76A','Yes','2025-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('03Q','QOQ','85J','Y63','76A','No','2024-04-01','2025-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('03Q','QOQ','85J','Y63','76A','Yes','2025-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('03R','QWO','85J','Y63','76A','No','2024-04-01','2025-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('03R','QWO','85J','Y63','76A','Yes','2025-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('03W','QK1','14A','Y60','14Q','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('04C','QK1','14A','Y60','14Q','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('04V','QK1','14A','Y60','14Q','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('04Y','QNC','14A','Y60','14Q','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('05D','QNC','14A','Y60','14Q','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('05G','QNC','14A','Y60','14Q','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('05Q','QNC','14A','Y60','14Q','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('05V','QNC','14A','Y60','14Q','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('05W','QNC','14A','Y60','14Q','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('06H','QUE','14E','Y61','14R','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('06K','QM7','14E','Y61','14R','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('06L','QJG','14E','Y61','14R','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('06N','QM7','14E','Y61','14R','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('06Q','QH8','14E','Y61','14R','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('06T','QJG','14E','Y61','14R','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('07G','QH8','14E','Y61','14R','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('07H','QM7','14E','Y61','14R','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('07K','QJG','14E','Y61','14R','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('09D','QNX','14G','Y59','97T','No','2024-04-01','2025-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('09D','QNX','14G','Y59','97T','Yes','2025-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('10Q','QU9','14G','Y59','97T','No','2024-04-01','2025-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('10Q','QU9','14G','Y59','97T','Yes','2025-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('10R','QRL','14G','Y59','97T','No','2024-04-01','2025-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('10R','QRL','14G','Y59','97T','Yes','2025-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('11J','QVV','14F','Y58','14T','No','2024-04-01','2025-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('11J','QVV','14F','Y58','14T','Yes','2025-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('11M','QR1','14F','Y58','14T','No','2024-04-01','2025-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('11M','QR1','14F','Y58','14T','Yes','2025-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('11N','QT6','14F','Y58','14T','No','2024-04-01','2025-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('11N','QT6','14F','Y58','14T','Yes','2025-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('11X','QSL','14F','Y58','14T','No','2024-04-01','2025-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('11X','QSL','14F','Y58','14T','Yes','2025-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('12F','QYG','27T','Y62','32T','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('13T','QHM','85J','Y63','76A','No','2024-04-01','2025-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('13T','QHM','85J','Y63','76A','Yes','2025-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('14L','QOP','27T','Y62','32T','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('14Y','QU9','14G','Y59','97T','No','2024-04-01','2025-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('14Y','QU9','14G','Y59','97T','Yes','2025-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('15A','QU9','14G','Y59','97T','No','2024-04-01','2025-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('15A','QU9','14G','Y59','97T','Yes','2025-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('15C','QUY','14F','Y58','14T','No','2024-04-01','2025-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('15C','QUY','14F','Y58','14T','Yes','2025-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('15E','QHL','14A','Y60','14Q','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('15F','QWO','85J','Y63','76A','No','2024-04-01','2025-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('15F','QWO','85J','Y63','76A','Yes','2025-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('15M','QJ2','14A','Y60','14Q','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('15N','QJK','14F','Y58','14T','No','2024-04-01','2025-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('15N','QJK','14F','Y58','14T','Yes','2025-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('16C','QHM','85J','Y63','76A','No','2024-04-01','2025-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('16C','QHM','85J','Y63','76A','Yes','2025-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('18C','QGH','14A','Y60','14Q','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('26A','QMM','14E','Y61','14R','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('27D','QYG','27T','Y62','32T','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('36J','QWO','85J','Y63','76A','No','2024-04-01','2025-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('36J','QWO','85J','Y63','76A','Yes','2025-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('36L','QWE','13R','Y56','14M','No','2024-04-01','2025-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('36L','QWE','13R','Y56','14M','Yes','2025-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('42D','QOQ','85J','Y63','76A','No','2024-04-01','2025-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('42D','QOQ','85J','Y63','76A','Yes','2025-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('52R','QT1','14A','Y60','14Q','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('70F','QNX','14G','Y59','97T','No','2024-04-01','2025-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('70F','QNX','14G','Y59','97T','Yes','2025-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('71E','QJM','14A','Y60','14Q','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('72Q','QKK','13R','Y56','14M','No','2024-04-01','2025-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('72Q','QKK','13R','Y56','14M','Yes','2025-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('78H','QPM','14A','Y60','14Q','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('84H','QHM','85J','Y63','76A','No','2024-04-01','2025-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('84H','QHM','85J','Y63','76A','Yes','2025-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('91Q','QKS','14G','Y59','97T','No','2024-04-01','2025-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('91Q','QKS','14G','Y59','97T','Yes','2025-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('92A','QXU','14G','Y59','97T','No','2024-04-01','2025-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('92A','QXU','14G','Y59','97T','Yes','2025-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('92G','QOX','14F','Y58','14T','No','2024-04-01','2025-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('92G','QOX','14F','Y58','14T','Yes','2025-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('93C','QMJ','13R','Y56','14M','No','2024-04-01','2025-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('93C','QMJ','13R','Y56','14M','Yes','2025-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('97R','QNX','14G','Y59','97T','No','2024-04-01','2025-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('97R','QNX','14G','Y59','97T','Yes','2025-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('99A','QYG','27T','Y62','32T','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('99C','QHM','85J','Y63','76A','No','2024-04-01','2025-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('99C','QHM','85J','Y63','76A','Yes','2025-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('99E','QH8','14E','Y61','14R','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('99F','QH8','14E','Y61','14R','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('99G','QH8','14E','Y61','14R','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('A3A8R','QMF','13R','Y56','14M','No','2024-04-01','2025-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('A3A8R','QMF','13R','Y56','14M','Yes','2025-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('B2M3M','QWU','14A','Y60','14Q','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('D2P2L','QUA','14A','Y60','14Q','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('D4U1Y','QNQ','14G','Y59','97T','No','2024-04-01','2025-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('D4U1Y','QNQ','14G','Y59','97T','Yes','2025-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('D9Y0V','QRL','14G','Y59','97T','No','2024-04-01','2025-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('D9Y0V','QRL','14G','Y59','97T','Yes','2025-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('M1J4Y','QHG','14E','Y61','14R','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('M2L0M','QOC','14A','Y60','14Q','Yes','2024-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('W2U3Z','QRV','13R','Y56','14M','No','2024-04-01','2025-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('W2U3Z','QRV','13R','Y56','14M','Yes','2025-04-01','2050-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('X2C4Y','QWO','85J','Y63','76A','No','2024-04-01','2025-03-31')
INSERT INTO [CAM_Ref].[SubICBtoDirectComm]([SubICB_Code],[ICB_Code],[ODSCommHub],[ODSRegion],[ODSHealthandJustice],[ProvisionalICBDelegationStatus],[Effective_From],[Effective_To])
     VALUES('X2C4Y','QWO','85J','Y63','76A','Yes','2025-04-01','2050-03-31')
